
language: java
after_success:
    - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
    - bash <(curl -s https://codecov.io/bash) -t 975ee89a-5871-435b-8593-e50005681082
notifications:
  slack:
    rooms:
      - comp3111h-group:LNziRF7cZV2So8b7DN046Xy9#automated
    on_success: always
    on_failure: always
  email:
    recipients:
      - mcding@connect.ust.hk
    on_success: never
    on_failure: never
