language: java
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi

notifications:
  slack:
    rooms:
      - comp3111h-group:VHx5gqZ97HVITVu271FgNsMb#general
    on_success: always
    on_failure: always
  email:
    recipients:
      - mcding@connect.ust.hk
    on_success: never
    on_failure: never