codecov:
  branch: develop
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 1
  round: down
  range: "20...100"

  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        only_pulls: false

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: no